spring:
  application:
    name: bookshop-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: bookshop_product_service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/**

            - id: bookshop_authentication
              uri: lb://AUTHENTICATION-SERVICE
              predicates:
                - Path=/auth/**
server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

